#!/bin/bash
/bin/bash ./install_all.sh >& ./some.log
while grep "Connection reset by peer" ./some.log ;
do
	cat " " > ./some.log;
	/bin/bash ./install_all.sh >& ./some.log;
	tail -n 1 ./some.log;
done
