pip install ipython
pip install tornado
pip install jinja2
pip install six
pip install pyzmq
pip install gevent
pip install pandas
pip install numpy
pip install matplotlib
pip install pillow
pip install mock
pip install PySide
pip install six
pip install scipy
pip install virtualenv
